interface ICountryData {
  code: string;
  name: string;
  phoneNumber: string;
  isPriority?: boolean;
}

const esfsCountriesData: ICountryData[] = [
  // Priority countries (displayed first)
  { code: 'BE', name: 'Belgium', phoneNumber: '+32', isPriority: true },
  { code: 'NL', name: 'Netherlands', phoneNumber: '+31', isPriority: true },
  { code: 'FR', name: 'France', phoneNumber: '+33', isPriority: true },
  { code: 'DE', name: 'Germany', phoneNumber: '+49', isPriority: true },
  { code: 'LU', name: 'Luxembourg', phoneNumber: '+352', isPriority: true },
  { code: 'ES', name: 'Spain', phoneNumber: '+34', isPriority: true },

  // Separator
  { code: '---', name: '---', phoneNumber: '---' },

  // All other countries
  { code: 'AF', name: 'Afghanistan', phoneNumber: '+93' },
  { code: 'AX', name: 'Aland Islands', phoneNumber: '+358' },
  { code: 'AL', name: 'Albania', phoneNumber: '+355' },
  { code: 'DZ', name: 'Algeria', phoneNumber: '+213' },
  { code: 'AS', name: 'AmericanSamoa', phoneNumber: '+1684' },
  { code: 'AD', name: 'Andorra', phoneNumber: '+376' },
  { code: 'AO', name: 'Angola', phoneNumber: '+244' },
  { code: 'AI', name: 'Anguilla', phoneNumber: '+1264' },
  { code: 'AQ', name: 'Antarctica', phoneNumber: '+672' },
  { code: 'AG', name: 'Antigua and Barbuda', phoneNumber: '+1268' },
  { code: 'AR', name: 'Argentina', phoneNumber: '+54' },
  { code: 'AM', name: 'Armenia', phoneNumber: '+374' },
  { code: 'AW', name: 'Aruba', phoneNumber: '+297' },
  { code: 'AU', name: 'Australia', phoneNumber: '+61' },
  { code: 'AT', name: 'Austria', phoneNumber: '+43' },
  { code: 'AZ', name: 'Azerbaijan', phoneNumber: '+994' },
  { code: 'BS', name: 'Bahamas', phoneNumber: '+1242' },
  { code: 'BH', name: 'Bahrain', phoneNumber: '+973' },
  { code: 'BD', name: 'Bangladesh', phoneNumber: '+880' },
  { code: 'BB', name: 'Barbados', phoneNumber: '+1246' },
  { code: 'BY', name: 'Belarus', phoneNumber: '+375' },
  { code: 'BZ', name: 'Belize', phoneNumber: '+501' },
  { code: 'BJ', name: 'Benin', phoneNumber: '+229' },
  { code: 'BM', name: 'Bermuda', phoneNumber: '+1441' },
  { code: 'BT', name: 'Bhutan', phoneNumber: '+975' },
  { code: 'BO', name: 'Bolivia, Plurinational State of', phoneNumber: '+591' },
  { code: 'BA', name: 'Bosnia and Herzegovina', phoneNumber: '+387' },
  { code: 'BW', name: 'Botswana', phoneNumber: '+267' },
  { code: 'BR', name: 'Brazil', phoneNumber: '+55' },
  { code: 'IO', name: 'British Indian Ocean Territory', phoneNumber: '+246' },
  { code: 'BN', name: 'Brunei Darussalam', phoneNumber: '+673' },
  { code: 'BG', name: 'Bulgaria', phoneNumber: '+359' },
  { code: 'BF', name: 'Burkina Faso', phoneNumber: '+226' },
  { code: 'BI', name: 'Burundi', phoneNumber: '+257' },
  { code: 'KH', name: 'Cambodia', phoneNumber: '+855' },
  { code: 'CM', name: 'Cameroon', phoneNumber: '+237' },
  { code: 'CA', name: 'Canada', phoneNumber: '+1' },
  { code: 'CV', name: 'Cape Verde', phoneNumber: '+238' },
  { code: 'KY', name: 'Cayman Islands', phoneNumber: '+ 345' },
  { code: 'CF', name: 'Central African Republic', phoneNumber: '+236' },
  { code: 'TD', name: 'Chad', phoneNumber: '+235' },
  { code: 'CL', name: 'Chile', phoneNumber: '+56' },
  { code: 'CN', name: 'China', phoneNumber: '+86' },
  { code: 'CX', name: 'Christmas Island', phoneNumber: '+61' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', phoneNumber: '+61' },
  { code: 'CO', name: 'Colombia', phoneNumber: '+57' },
  { code: 'KM', name: 'Comoros', phoneNumber: '+269' },
  { code: 'CG', name: 'Congo', phoneNumber: '+242' },
  {
    code: 'CD',
    name: 'Congo, The Democratic Republic of the Congo',
    phoneNumber: '+243',
  },
  { code: 'CK', name: 'Cook Islands', phoneNumber: '+682' },
  { code: 'CR', name: 'Costa Rica', phoneNumber: '+506' },
  { code: 'CI', name: "Cote d'Ivoire", phoneNumber: '+225' },
  { code: 'HR', name: 'Croatia', phoneNumber: '+385' },
  { code: 'CU', name: 'Cuba', phoneNumber: '+53' },
  { code: 'CY', name: 'Cyprus', phoneNumber: '+357' },
  { code: 'CZ', name: 'Czech Republic', phoneNumber: '+420' },
  { code: 'DK', name: 'Denmark', phoneNumber: '+45' },
  { code: 'DJ', name: 'Djibouti', phoneNumber: '+253' },
  { code: 'DM', name: 'Dominica', phoneNumber: '+1767' },
  { code: 'DO', name: 'Dominican Republic', phoneNumber: '+1849' },
  { code: 'EC', name: 'Ecuador', phoneNumber: '+593' },
  { code: 'EG', name: 'Egypt', phoneNumber: '+20' },
  { code: 'SV', name: 'El Salvador', phoneNumber: '+503' },
  { code: 'GQ', name: 'Equatorial Guinea', phoneNumber: '+240' },
  { code: 'ER', name: 'Eritrea', phoneNumber: '+291' },
  { code: 'EE', name: 'Estonia', phoneNumber: '+372' },
  { code: 'ET', name: 'Ethiopia', phoneNumber: '+251' },
  { code: 'FK', name: 'Falkland Islands (Malvinas)', phoneNumber: '+500' },
  { code: 'FO', name: 'Faroe Islands', phoneNumber: '+298' },
  { code: 'FJ', name: 'Fiji', phoneNumber: '+679' },
  { code: 'FI', name: 'Finland', phoneNumber: '+358' },
  { code: 'GF', name: 'French Guiana', phoneNumber: '+594' },
  { code: 'PF', name: 'French Polynesia', phoneNumber: '+689' },
  { code: 'GA', name: 'Gabon', phoneNumber: '+241' },
  { code: 'GM', name: 'Gambia', phoneNumber: '+220' },
  { code: 'GE', name: 'Georgia', phoneNumber: '+995' },
  { code: 'GH', name: 'Ghana', phoneNumber: '+233' },
  { code: 'GI', name: 'Gibraltar', phoneNumber: '+350' },
  { code: 'GR', name: 'Greece', phoneNumber: '+30' },
  { code: 'GL', name: 'Greenland', phoneNumber: '+299' },
  { code: 'GD', name: 'Grenada', phoneNumber: '+1473' },
  { code: 'GP', name: 'Guadeloupe', phoneNumber: '+590' },
  { code: 'GU', name: 'Guam', phoneNumber: '+1671' },
  { code: 'GT', name: 'Guatemala', phoneNumber: '+502' },
  { code: 'GG', name: 'Guernsey', phoneNumber: '+44' },
  { code: 'GN', name: 'Guinea', phoneNumber: '+224' },
  { code: 'GW', name: 'Guinea-Bissau', phoneNumber: '+245' },
  { code: 'GY', name: 'Guyana', phoneNumber: '+595' },
  { code: 'HT', name: 'Haiti', phoneNumber: '+509' },
  { code: 'VA', name: 'Holy See (Vatican City State)', phoneNumber: '+379' },
  { code: 'HN', name: 'Honduras', phoneNumber: '+504' },
  { code: 'HK', name: 'Hong Kong', phoneNumber: '+852' },
  { code: 'HU', name: 'Hungary', phoneNumber: '+36' },
  { code: 'IS', name: 'Iceland', phoneNumber: '+354' },
  { code: 'IN', name: 'India', phoneNumber: '+91' },
  { code: 'ID', name: 'Indonesia', phoneNumber: '+62' },
  {
    code: 'IR',
    name: 'Iran, Islamic Republic of Persian Gulf',
    phoneNumber: '+98',
  },
  { code: 'IQ', name: 'Iraq', phoneNumber: '+964' },
  { code: 'IE', name: 'Ireland', phoneNumber: '+353' },
  { code: 'IM', name: 'Isle of Man', phoneNumber: '+44' },
  { code: 'IL', name: 'Israel', phoneNumber: '+972' },
  { code: 'IT', name: 'Italy', phoneNumber: '+39' },
  { code: 'JM', name: 'Jamaica', phoneNumber: '+1876' },
  { code: 'JP', name: 'Japan', phoneNumber: '+81' },
  { code: 'JE', name: 'Jersey', phoneNumber: '+44' },
  { code: 'JO', name: 'Jordan', phoneNumber: '+962' },
  { code: 'KZ', name: 'Kazakhstan', phoneNumber: '+77' },
  { code: 'KE', name: 'Kenya', phoneNumber: '+254' },
  { code: 'KI', name: 'Kiribati', phoneNumber: '+686' },
  {
    code: 'KP',
    name: "Korea, Democratic People's Republic of Korea",
    phoneNumber: '+850',
  },
  { code: 'KR', name: 'Korea, Republic of South Korea', phoneNumber: '+82' },
  { code: 'KW', name: 'Kuwait', phoneNumber: '+965' },
  { code: 'KG', name: 'Kyrgyzstan', phoneNumber: '+996' },
  { code: 'LA', name: 'Laos', phoneNumber: '+856' },
  { code: 'LV', name: 'Latvia', phoneNumber: '+371' },
  { code: 'LB', name: 'Lebanon', phoneNumber: '+961' },
  { code: 'LS', name: 'Lesotho', phoneNumber: '+266' },
  { code: 'LR', name: 'Liberia', phoneNumber: '+231' },
  { code: 'LY', name: 'Libyan Arab Jamahiriya', phoneNumber: '+218' },
  { code: 'LI', name: 'Liechtenstein', phoneNumber: '+423' },
  { code: 'LT', name: 'Lithuania', phoneNumber: '+370' },
  { code: 'MO', name: 'Macao', phoneNumber: '+853' },
  { code: 'MK', name: 'Macedonia', phoneNumber: '+389' },
  { code: 'MG', name: 'Madagascar', phoneNumber: '+261' },
  { code: 'MW', name: 'Malawi', phoneNumber: '+265' },
  { code: 'MY', name: 'Malaysia', phoneNumber: '+60' },
  { code: 'MV', name: 'Maldives', phoneNumber: '+960' },
  { code: 'ML', name: 'Mali', phoneNumber: '+223' },
  { code: 'MT', name: 'Malta', phoneNumber: '+356' },
  { code: 'MH', name: 'Marshall Islands', phoneNumber: '+692' },
  { code: 'MQ', name: 'Martinique', phoneNumber: '+596' },
  { code: 'MR', name: 'Mauritania', phoneNumber: '+222' },
  { code: 'MU', name: 'Mauritius', phoneNumber: '+230' },
  { code: 'YT', name: 'Mayotte', phoneNumber: '+262' },
  { code: 'MX', name: 'Mexico', phoneNumber: '+52' },
  {
    code: 'FM',
    name: 'Micronesia, Federated States of Micronesia',
    phoneNumber: '+691',
  },
  { code: 'MD', name: 'Moldova', phoneNumber: '+373' },
  { code: 'MC', name: 'Monaco', phoneNumber: '+377' },
  { code: 'MN', name: 'Mongolia', phoneNumber: '+976' },
  { code: 'ME', name: 'Montenegro', phoneNumber: '+382' },
  { code: 'MS', name: 'Montserrat', phoneNumber: '+1664' },
  { code: 'MA', name: 'Morocco', phoneNumber: '+212' },
  { code: 'MZ', name: 'Mozambique', phoneNumber: '+258' },
  { code: 'MM', name: 'Myanmar', phoneNumber: '+95' },
  { code: 'NA', name: 'Namibia', phoneNumber: '+264' },
  { code: 'NR', name: 'Nauru', phoneNumber: '+674' },
  { code: 'NP', name: 'Nepal', phoneNumber: '+977' },
  { code: 'AN', name: 'Netherlands Antilles', phoneNumber: '+599' },
  { code: 'NC', name: 'New Caledonia', phoneNumber: '+687' },
  { code: 'NZ', name: 'New Zealand', phoneNumber: '+64' },
  { code: 'NI', name: 'Nicaragua', phoneNumber: '+505' },
  { code: 'NE', name: 'Niger', phoneNumber: '+227' },
  { code: 'NG', name: 'Nigeria', phoneNumber: '+234' },
  { code: 'NU', name: 'Niue', phoneNumber: '+683' },
  { code: 'NF', name: 'Norfolk Island', phoneNumber: '+672' },
  { code: 'MP', name: 'Northern Mariana Islands', phoneNumber: '+1670' },
  { code: 'NO', name: 'Norway', phoneNumber: '+47' },
  { code: 'OM', name: 'Oman', phoneNumber: '+968' },
  { code: 'PK', name: 'Pakistan', phoneNumber: '+92' },
  { code: 'PW', name: 'Palau', phoneNumber: '+680' },
  { code: 'PS', name: 'Palestinian Territory, Occupied', phoneNumber: '+970' },
  { code: 'PA', name: 'Panama', phoneNumber: '+507' },
  { code: 'PG', name: 'Papua New Guinea', phoneNumber: '+675' },
  { code: 'PY', name: 'Paraguay', phoneNumber: '+595' },
  { code: 'PE', name: 'Peru', phoneNumber: '+51' },
  { code: 'PH', name: 'Philippines', phoneNumber: '+63' },
  { code: 'PN', name: 'Pitcairn', phoneNumber: '+872' },
  { code: 'PL', name: 'Poland', phoneNumber: '+48' },
  { code: 'PT', name: 'Portugal', phoneNumber: '+351' },
  { code: 'PR', name: 'Puerto Rico', phoneNumber: '+1939' },
  { code: 'QA', name: 'Qatar', phoneNumber: '+974' },
  { code: 'RO', name: 'Romania', phoneNumber: '+40' },
  { code: 'RU', name: 'Russia', phoneNumber: '+7' },
  { code: 'RW', name: 'Rwanda', phoneNumber: '+250' },
  { code: 'RE', name: 'Reunion', phoneNumber: '+262' },
  { code: 'BL', name: 'Saint Barthelemy', phoneNumber: '+590' },
  {
    code: 'SH',
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    phoneNumber: '+290',
  },
  { code: 'KN', name: 'Saint Kitts and Nevis', phoneNumber: '+1869' },
  { code: 'LC', name: 'Saint Lucia', phoneNumber: '+1758' },
  { code: 'MF', name: 'Saint Martin', phoneNumber: '+590' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', phoneNumber: '+508' },
  {
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    phoneNumber: '+1784',
  },
  { code: 'WS', name: 'Samoa', phoneNumber: '+685' },
  { code: 'SM', name: 'San Marino', phoneNumber: '+378' },
  { code: 'ST', name: 'Sao Tome and Principe', phoneNumber: '+239' },
  { code: 'SA', name: 'Saudi Arabia', phoneNumber: '+966' },
  { code: 'SN', name: 'Senegal', phoneNumber: '+221' },
  { code: 'RS', name: 'Serbia', phoneNumber: '+381' },
  { code: 'SC', name: 'Seychelles', phoneNumber: '+248' },
  { code: 'SL', name: 'Sierra Leone', phoneNumber: '+232' },
  { code: 'SG', name: 'Singapore', phoneNumber: '+65' },
  { code: 'SK', name: 'Slovakia', phoneNumber: '+421' },
  { code: 'SI', name: 'Slovenia', phoneNumber: '+386' },
  { code: 'SB', name: 'Solomon Islands', phoneNumber: '+677' },
  { code: 'SO', name: 'Somalia', phoneNumber: '+252' },
  { code: 'ZA', name: 'South Africa', phoneNumber: '+27' },
  { code: 'SS', name: 'South Sudan', phoneNumber: '+211' },
  {
    code: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    phoneNumber: '+500',
  },
  { code: 'LK', name: 'Sri Lanka', phoneNumber: '+94' },
  { code: 'SD', name: 'Sudan', phoneNumber: '+249' },
  { code: 'SR', name: 'Suriname', phoneNumber: '+597' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', phoneNumber: '+47' },
  { code: 'SZ', name: 'Swaziland', phoneNumber: '+268' },
  { code: 'SE', name: 'Sweden', phoneNumber: '+46' },
  { code: 'CH', name: 'Switzerland', phoneNumber: '+41' },
  { code: 'SY', name: 'Syrian Arab Republic', phoneNumber: '+963' },
  { code: 'TW', name: 'Taiwan', phoneNumber: '+886' },
  { code: 'TJ', name: 'Tajikistan', phoneNumber: '+992' },
  {
    code: 'TZ',
    name: 'Tanzania, United Republic of Tanzania',
    phoneNumber: '+255',
  },
  { code: 'TH', name: 'Thailand', phoneNumber: '+66' },
  { code: 'TL', name: 'Timor-Leste', phoneNumber: '+670' },
  { code: 'TG', name: 'Togo', phoneNumber: '+228' },
  { code: 'TK', name: 'Tokelau', phoneNumber: '+690' },
  { code: 'TO', name: 'Tonga', phoneNumber: '+676' },
  { code: 'TT', name: 'Trinidad and Tobago', phoneNumber: '+1868' },
  { code: 'TN', name: 'Tunisia', phoneNumber: '+216' },
  { code: 'TR', name: 'Turkey', phoneNumber: '+90' },
  { code: 'TM', name: 'Turkmenistan', phoneNumber: '+993' },
  { code: 'TC', name: 'Turks and Caicos Islands', phoneNumber: '+1649' },
  { code: 'TV', name: 'Tuvalu', phoneNumber: '+688' },
  { code: 'UG', name: 'Uganda', phoneNumber: '+256' },
  { code: 'UA', name: 'Ukraine', phoneNumber: '+380' },
  { code: 'AE', name: 'United Arab Emirates', phoneNumber: '+971' },
  { code: 'GB', name: 'United Kingdom', phoneNumber: '+44' },
  { code: 'US', name: 'United States', phoneNumber: '+1' },
  { code: 'UY', name: 'Uruguay', phoneNumber: '+598' },
  { code: 'UZ', name: 'Uzbekistan', phoneNumber: '+998' },
  { code: 'VU', name: 'Vanuatu', phoneNumber: '+678' },
  {
    code: 'VE',
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    phoneNumber: '+58',
  },
  { code: 'VN', name: 'Vietnam', phoneNumber: '+84' },
  { code: 'VG', name: 'Virgin Islands, British', phoneNumber: '+1284' },
  { code: 'VI', name: 'Virgin Islands, U.S.', phoneNumber: '+1340' },
  { code: 'WF', name: 'Wallis and Futuna', phoneNumber: '+681' },
  { code: 'YE', name: 'Yemen', phoneNumber: '+967' },
  { code: 'ZM', name: 'Zambia', phoneNumber: '+260' },
  { code: 'ZW', name: 'Zimbabwe', phoneNumber: '+263' },
];

// Export original API - phone countries array
export const esfsPhoneCountries = esfsCountriesData.map((country) => ({
  number: country.phoneNumber,
  code: country.code,
}));

// Export country names as object for backward compatibility
export const esfsCountryNames = esfsCountriesData.reduce((acc, country) => {
  acc[country.code] = country.name;
  return acc;
}, {} as Record<string, string>);

// Export comprehensive data for advanced use cases
export { esfsCountriesData };

// Export utility functions
export const getCountryByCode = (code: string): ICountryData | undefined =>
  esfsCountriesData.find((country) => country.code === code);

export const getCountryByPhoneNumber = (
  phoneNumber: string
): ICountryData | undefined =>
  esfsCountriesData.find((country) => country.phoneNumber === phoneNumber);
